services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${CLIENT_PORT}:3000'

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${SERVER_PORT}:3000'

